### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ricardovigatti** [spatie/laravel-view-models#7]
Man, sorry to ask u that but, what are the differences between this package and View Composers?

**Comment by freekmurze** [comment]
Read this blogpost: https://stitcher.io/blog/laravel-view-models

**Comment by ricardovigatti** [comment]
I've already read it. He approaches doesn't differs much from private methods in a controller. He is only dispatching things to another class, and in a very verbose way.

That's why i'm asking this, if is for doing this, view composers do the same using a better approach

**Comment by brendt** [comment]
@ricardovigatti definitely not. View composers are registered as global configuration, they are very implicit in their way of passing data to a controller.

Take a look at the following example:

```php
class MyController
{
    public function index()
    {
        return view('my.index');
    }
}
```

Can you tell me which variables are available to the view from reading this code snippet, if you're using view composers? Nope. 

Now compare it to this:

```php
class MyController
{
    public function index()
    {
        return view('my.index', new MyViewModel(/* … */));
    }
}
```

ViewModels are not a nasty hack in support of RAD. We use them to make our code more explicit and maintainable when working on large projects with multiple developers. It's not because the end result is the same, that both means to that end can be compared.

**Comment by brendt** [comment]
Also, a new writeup answering the question even more in-depth: https://stitcher.io/blog/laravel-view-models-vs-view-composers
